add:tag_name validation

diff --git a/.github/workflows/create-tag-and-release-draft.yaml b/.github/workflows/create-tag-and-release-draft.yaml
--- a/.github/workflows/create-tag-and-release-draft.yaml
+++ b/.github/workflows/create-tag-and-release-draft.yaml
@@ -17,19 +17,29 @@ permissions:
 
 jobs:
   create-tag:
+    name: create-tag
     runs-on: ubuntu-latest
     steps:
+      - run: |
+          echo "check tag_name"
+          echo $TAG_NAME | grep -o -E "^(v[0-9]+\.){1}[0-9]+(\.[0-9]+)$"
+          if [ $? -ne 0 ]; then
+            echo "Error: $TAG_NAME is invalid. Please enter 'vX.X.X'"
+            exit 1
+          fi
       - uses: actions/checkout@v2
         with:
           # ターゲットブランチをmainに固定
           ref: main
-          # 既存のタグを上書きしないようにfetchしておく。誤って既存タグを入力した場合「git tag」コマンドでエラーとなる。
+          # 既存のタグを上書きしないようにfetchしておく。誤って既存タグを入力した場合「git tag」コマンドで重複エラーとなる。
           fetch-depth: 0
       - run: |
           git tag $TAG_NAME
           git push origin $TAG_NAME
 
   create-release-draft:
+    name: create-release-draft
+    needs: create-tag
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
